# Generated by Django 4.2.1 on 2023-06-02 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("register", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerecord",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="register.car"
            ),
        ),
        migrations.AddField(
            model_name="servicerecord",
            name="service_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer.servicetype"
            ),
        ),
        migrations.AddField(
            model_name="servicerecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
