# Generated by Django 4.2.1 on 2023-05-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(verbose_name="生日"),
        ),
    ]
